wandb: true
wandb_project: 'BoltzNCE_alanine'
wandb_name: 'vector_field_trainining_ot_endpoint_tmax100'
save_vector_field_checkpoint: 'saved_models/trained_vector_5_layer_ot_endpoint_tmax100.pt'
config_save_name: 'saved_models/trained_vector_5_layer_ot_endpoint_tmax100.yaml'
model_type: 'vector_field'
ema: false

interpolant:
  ot: true

dataloader:
  dataset: '../data/AD2_relaxed.npy'

train_vector:
  endpoint: true
  tweight_max: 100.0
