wandb: true
wandb_project: 'BoltzNCE_alanine'
wandb_name: 'vector_field_trainining_ot'
save_vector_field_checkpoint: 'saved_models/trained_vector_5_layer_ot.pt'
config_save_name: 'saved_models/trained_vector_5_layer_ot.yaml'
model_type: 'vector_field'

interpolant:
  ot: true

dataloader:
  dataset: '../data/AD2_relaxed.npy'